# Generated by Django 3.2.7 on 2021-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': '景点', 'verbose_name_plural': '景点'},
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='景点描述'),
        ),
        migrations.AlterField(
            model_name='award',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Award/', verbose_name='景点照片'),
        ),
    ]
