# Generated by Django 2.2.4 on 2024-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0002_auto_20240320_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('一日游', '一日游'), ('多日游', '多日游'), ('亲子游', '亲子游')], max_length=50, verbose_name='产品类型'),
        ),
    ]
