# Generated by Django 2.2.4 on 2024-03-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0003_auto_20240320_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('一日游', '一日游'), ('多日游', '多日游'), ('亲子游', '亲子游')], max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='productsApp.Product', verbose_name='旅游团'),
        ),
    ]
