# Generated by Django 2.2.4 on 2024-03-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_mynew_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
